listen:
  webNetwork: "tcp4"
  web: ":8080"
  webMethod: "http"
  identify: true
serve:
  dataStorage: ""
  domains: []
  rangeSupported: true
  enableGoInfoPage: true
  cacheSettings:
    enableTemplateCaching: false
    enableTemplateCachePurge: false
    enableContentsCaching: true
    enableContentsCachePurge: true
    maxAge: 3600
    notModifiedUsingLastModified: true
    notModifiedUsingETags: true